apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homework-central
resources:
  - service-account.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
  - hpa.yaml
  - pdb.yaml
labels:
  - pairs:
      app.kubernetes.io/name: llm
      app.kubernetes.io/part-of: homework-central
